### ISSUE TITLE
스터디용 저장소 생성했음

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#10]
https://github.com/zrma/newboy/

마찬가지로 trunk 안에 프로젝트 하나씩 주제별로 만들어서 소스 관리 하면 될 듯

**Comment by trizdreaming** [comment]
네~ 벌써 집어넣었습니다~~ㅎㅎ

**Comment by zrma** [comment]
스터디 잘 진행하고 있으므로 닫음 :)
