### ISSUE TITLE
전체적 피드백 - oldboy.h 헤더 파일 정리 및 필터 이름 변경

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#103]
=== 전체적인 피드백

1.
oldboy.h를 보면 라이브러리 관련 헤더들을 인클루드 해 놓아고,
실제로 이 라이브러리 헤더들이 필요가 없는 cpp 파일에서도 #include "oldboy.h"를 일괄적으로 쓰고 있다.
이렇게 하지 말고, 헤더 인클루드는 cpp 파일 마다 꼭 필요한 것만 할 것.

다시 한 번 말하지만, 헤더 인클루드를 위한 헤더 파일은 stdafx.h 말고 하지 말 것.

https://github.com/trizdreaming/oldboy/blob/03ee281c7f3e96b966c6ec644b89afff88ecc2c5/oldboy/oldboy/oldboy.h

2.
직접 게임에 관련된 구현은 Core라는 필터에 모두 모아 놓았는데, 필터 이름 바꿀 것.
실제 게임 이름인 리듬매치라던가...
보통 Core라고 해놓으면 라이브러리 핵심 로직들 모아 놓는 곳을 의미

**Comment by zrma** [comment]
ad181d2a1153ef4c4a6405e4bdbdbaa7079ab113
1. 헤더 파일을 한 땀 한 땀 집어넣었음
2. oldboy.h 헤더파일이 통째로 사라졌음

앞으로 필요할 때 마다 RMdefine.h이나 RMmacro.h를 손수 include 해야 함

a8d78bb870c9530887ad19ae42e8d6a027653818
1. 필터 이름 정리하였음

확인 후 클로즈

**Comment by flashscope** [comment]
확인 동찬이형 클로즈 부탁드립니다.

**Comment by trizdreaming** [comment]
확인했습니다. oldboy.h 편했는데 안타깝네요.
