### ISSUE TITLE
const 이슈 처리

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#109]
float                        GetWidth() const { return m_Width; } //SM9: 이렇게 멤버 변수의 상태를 바꾸지 않는 함수의 경우 최대한 const를 붙여라

const 붙이기

RMimage.h
RMlabelManager.cpp 
RMlabelManager.h 
RMresourceManager.h
RMxmlLoader.h

**Comment by zrma** [comment]
2efd23ab9729774a4b52ab5d0865fff63c7de658

1차로 수정 하였음

Label 매니저 변경 후 CRMobjectManager 변경해야 함

**Comment by trizdreaming** [comment]
2차로 수정 완료
