### ISSUE TITLE
[피드백] 게임 컨셉 및 스터디 저널

### ISSUE THREAD

**Issue by zeliard** [trizdreaming/oldboy#11]
이번 주 피드백 드립니다.

A. 게임 컨셉 부분 (1점 감점)

요약 형식으로 기획서를 작성해놓아서 정확한 플레이 형태가 그려지지 않습니다. (대충 감으로는 어떻게 돌아가는지 추측은 됩니다만) 
- 노트 종류가 대체 몇 개인지? (키로 바인딩 된 표를 봐서는 1개인 것 같은데, 프로토타입을 봐서는 2개인 것 같기도 하고? 태고의 북 스타일??)
  - 셔터와 노트의 연계가 어떻게 되는지?

아무튼, 이해가 쉽도록 좀 더 세밀한 그림을 그려줄 필요가 있습니다.

그리고, 몇 가지 빠진 사항이 있습니다.
- 만들고자 하는 게임은 어떤 유저를 타겟(대상)으로 하는가?
  (예: 평소에 DJMAX와 같은 리듬 게임을 주로 하는 사람?)
- 그 유저에게 어떤 경험을 주고자 하는가? 
  (예: 음악적 감각과 컨트롤을 통한 상황 제어의 묘미?? )

B. 스터디 저널 (1점 감점)

스터디 저널은 "~~내용을 공부했다"를 남기는 것이 아니라 실제로 그 내용 자체가 남아 있어야 합니다. 즉, 제 3자가 봤을때, 그 내용을 보고 공부할 수 있는 수준이 되어야 합니다. 
예를 들어, D2D 항목( https://github.com/trizdreaming/oldboy/wiki/1%EC%A3%BC%EC%B0%A8-%ED%95%99%EC%8A%B5 )을 보면 실제 공부한 내용 요약이 없고 제목만 있습니다.

**Comment by zrma** [comment]
감사합니다!

### 이번 주 차 수정 및 보완 요구 사항 정리

---

#### 1. 컨셉 기획서 수정 보완 : 타겟층, 전달경험, 인터페이스, 플레이 시나리오 재정리 및 그에 근거한 흥미곡선 등.

---
- 주요 목표
  <br>a) 전체를 관통 할 수 있는 큰 그림을 먼저 전달하기
  <br>b) 세부 요소들은 한 눈에 들어올 수 있는 핵심 단어를 골라 명확하고 간결하게 전달
  <br>c) 인터페이스는 부분 부분 별로 나누어 어떤 기능이 무슨 역할을 하는지 정확히 묘사
  <br>d) 1인칭 시점의 플레이 시나리오를 가상 소설로 작성.

---

#### 2. 스터디 저널 -> 확실한 결과물을 기반으로 한 풀이 설명(누구나 쉽게 따라 할 수 있는 정도로)

---
- 주요 목표
  <br>a) D2D 스터디 내용 구체화(코드 구현물이 없으므로 PPT 자료를 이미지 첨부)
  <br>b) FSM 모델의 실제 사용 예제 작성 첨부(간단하게 NPC 케릭터의 행동 패턴을 FSM 모델로 작성한 Class 파일 첨부)

<br>이 정도로 정리를 해 보완하겠습니다.

**Comment by zeliard** [comment]
다 처리 되었으면 닫아주세요..

**Comment by zrma** [comment]
넵 어제 저녁 (10/14-월) 완료 되었으므로 이 이슈는 닫겠습니다.
