### ISSUE TITLE
RMlabel.h 이슈 처리

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#111]
// wchar_t\*        m_String;
        wchar_t                m_String[255]; //SM9: 255 이런거 define으로 빼던가 (나중에 버퍼 오버플로의 주범이 될 수있는 코드) 그냥 string 쓰던가..

**Comment by flashscope** [comment]
wstring을 string으로 바꿀 수 있나요?

**Comment by zrma** [comment]
변경 처리 완료
