### ISSUE TITLE
RMmainLoop.cpp 이슈

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#113]
m_PlayMusicName("") //SM9: 스트링 같은 애들은 이렇게 초기화 할 필요 없다. 자체 생성자에서 초기화 해줌.

//===================================================================
        // 음악 데이터를 불러온다.
        //SM9: 이런거는 에러처리 잘 해주어야 한다. 만일 음악 데이터 불러오는게 실패하더라도 문제 없는지? 
        LoadMusicData();

```
   // test 음악선택하기
    //SM9: 위에서 LoadMusicData가 실패했다면 여기서 포인터 참조 에러 나겠지...
    m_PlayMusicName = *( m_MusicList.begin() );
```

 CRMlabel\*        testLabel = new CRMlabel();
                                wchar_t                testChar[255] = {0, };
                                swprintf_s(testChar, L"FPS : %d ", fps); //SM9: fps 같은 지역 변수는 가장 처음 쓰이는 곳 바로 윗쪽에 두는게 코드 보기 편하다.

void CRMmainLoop::LoadMusicData()
{
        WIN32_FIND_DATAA findFileData;
        HANDLE hFind = FindFirstFileA( MUSIC_FOLDER_SEARCH, &findFileData ); //SM9: ASCII 전용 함수를 쓰는 이유는? 라이브러리 호환성 때문에 그런가?

```
    for ( int i = 0 ; i < 20 ; ++ i ) //SM9: 20?? DEFINE같은거로 빼고, 네이밍 잘 해야 의미가 명백해진다.
    {
            testObject = new CRMchildEffectImage();
            testObject->SetObjectType(OBJECT_NOTE_HIT);
            testObject->SetPosition(DEFAULT_POSITION_X, DEFAULT_POSITION_Y);
            testObject->SetSceneType(SCENE_PLAY);
            CRMobjectManager::GetInstance()->AddObject(testObject, LAYER_NOTE_HIT);
    }
```

노트 메모리풀에 100개 생성해서 넣을 때 100도 DEFINE으로 뽑아야 함

**Comment by zrma** [comment]
"" 초기화 제거 하였음

음악 데이터 초기화 관련 HRESULT 리턴하여 예외 처리 해 줌

fps 지역변수가 while루프 안에서 돌면서 계속 사용 되므로 while 루프 상단에서 처음부터 선언 및 초기화 해 줌

라이브러리 호환성 문제 때문에 std::wstring 을 일괄적으로 std::string으로 변환하는데는 문제가 있어보임
https://github.com/trizdreaming/oldboy/issues/128
참고

노트 메모리풀에 넣는 값 등 상수화 완료

확인 후 클로즈

**Comment by flashscope** [comment]
확인
