### ISSUE TITLE
RMmusicData.h

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#114]
CRMmusicData
                (
                std::string title,
                std::string artist,
                std::string level,
                std::string ImageBackground,
                std::string ImageShutter,
                std::string ImageNote1,
                std::string ImageNote2,
                std::string ImageNoteEffect,
                std::string SoundBackground,
                std::string SoundNoteEffect1,
                std::string SoundNoteEffect2,
                std::string Note
                ); //SM9: 이것들도 const string& 으로 넘기지?
        ~CRMmusicData(void);

public:
        const std::string\*                GetTitle() { return &m_title; } // SM9: const string&으로 리턴하는게 쓰기 편할듯?
        const std::string\*                GetArtist() { return &m_artist; }
        const std::string\*                GetLevel() { return &m_level; }
        const std::string\*                GetImageBackground() { return &m_ImageBackground; }
        const std::string\*                GetImageShutter() { return &m_ImageShutter; }
        const std::string\*                GetImageNote1() { return &m_ImageNote1; }
        const std::string\*                GetImageNote2() { return &m_ImageNote2; }
        const std::string\*                GetImageNoteEffect() { return &m_ImageNoteEffect; }
        const std::string\*                GetSoundBackground() { return &m_SoundBackground; }
        const std::string\*                GetSoundNoteEffect1() { return &m_SoundNoteEffect1; }
        const std::string\*                GetSoundNoteEffect2() { return &m_SoundNoteEffect2; }
        const std::string\*                GetNote() { return &m_Note; }

**Comment by flashscope** [comment]
처리 완료
https://github.com/trizdreaming/oldboy/commit/f022b5dc748b0a59f894b2567b8f84b8f8d27592
