### ISSUE TITLE
RMvideoPlayer.cpp 이슈 처리

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#116]
m_Buffer = m_BandiVideoTexture->Lock( m_Pitch ); //SM9: 반드시 Unlock됨을 보장하는가? m_Buffer값으로 판단이 되남?

 Sleep(1); //SM9: 이유는?

이곳은 주석처리로 풀이를 써 두면 될 듯

**Comment by zrma** [comment]
37d7d0afe764e9709f093f3d9d33eda265a86c0e

일단 임시방편으로 이렇게 함

m_BandiVideoTexture 내부에서 Lock이 걸렸는지 확인하는 함수를 찾거나 해서
변경 해야 할 듯?

**Comment by zrma** [comment]
m_BandiVideoTexture는 IDirect3DTexture9 포인터이고,

반디비디오 라이브러리에서 LockRect를 호출하면 텍스쳐의 rectangle 영역에 Lock을 시도하고
그 결과를 HRESULT로 리턴해 주는데, 라이브러리 쪽에서 관련하여 에러 처리를 하지 않음.

**Comment by flashscope** [comment]
확인
