### ISSUE TITLE
RMxmlLoader.cpp 이슈 처리

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#117]
void CRMxmlLoader::LoadMusicData(const std::string& folderName ) //SM9: folderName이 아래에서 바뀌지 않으므로 이렇게 const..
{

```
    std::string filePath = "";
```

**Comment by flashscope** [comment]
처리 완료
https://github.com/trizdreaming/oldboy/commit/3ad5ac260cb7c6a63b0f20206d50b44c3057deec
