### ISSUE TITLE
C++ 엔진과 C# 툴의 연동 자료

### ISSUE THREAD

**Issue by agebreak** [trizdreaming/oldboy#12]
C#으로 툴을 개발한다고 해서, 예전에 KGC 2011에서 발표되었던 좋은 참고 자료를 올립니다..
http://kallru.com/blog/1169361907

꼭 읽어보세요~ 두번 읽어보세요~

**Comment by zrma** [comment]
감사합니다!!! :) 세 번 읽어볼게요 ㅋㅋ

**Comment by trizdreaming** [comment]
감사합니다~!!

**Comment by zrma** [comment]
멤버들 모두 자료를 확인하였으므로 해당 이슈를 닫겠습니다.
