### ISSUE TITLE
배포 버전 실행 오류 발생 'message 확인 바람'

### ISSUE THREAD

**Issue by trizdreaming** [trizdreaming/oldboy#120]
프로시저 시작 지점 _crtCreateSymbolicLinkW를 DLL C:\Windows\SYSTEM32\MSVCP110.dll에서 찾을 수 없습니다.

**Comment by trizdreaming** [comment]
http://wnguswlssla.blog.me/130176924026 파일 다운로드 참고

**Comment by flashscope** [comment]
다음번 패키징에서 포함하여 같이 설치하도록 함
