### ISSUE TITLE
CPU 과부하 문제

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#121]
페러럴 환경이지만 CPU 50%다 찍어 버림
fps는 60유지하는데 프레임 버벅은 생김

**Comment by flashscope** [comment]
aabe4ac65711b45509374727b082aa021c498cc5
CPU사용률 10~20%정도 하락

메인 루프에서 fps계산 부분이 필요할까요?

**Comment by zrma** [comment]
FPS 계산은 일단 필요할 듯?

75e69cb05a6b381a0147cf5ea32c0b2f0ba4caa0
일단 디버깅 모드에서만 FPS 계산을 하도록 변경함

**Comment by flashscope** [comment]
확인
