### ISSUE TITLE
승자 판정 문제를 고민해봅시다.

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#123]
1. 게임 플레이 도중 2p가 셔터가 다 내려가 게임 오버가 되었다 (2p 패배 확정)

2.1p는 노래가 끝날때 까지 계속 혼자 플레이를 한다.

3.1p가 혼자 플레이를 하다가 노래가 끝나기 전에 죽었다.

4.노래가 중단이 되고 result화면이 나왔는데

5.1p는 win인가 draw인가 아니면 다른 무엇인가.

1p에 대한 처리를 어떻게 해야할지 의견주세요

**Comment by zrma** [comment]
1번째 방안.

위에 묘사한 시나리오대로면 1P의 승리가 확정 된 시점 이후로 

노래를 완성하면 Success, 완성 못 하면 Fail

Win & Success  /  Win & Fail
이런 결과로 나올 듯

이런 방식으로 된다면
1P와 2P 모두 곡을 완료할 때 까지 대결에서 승부가 결정 지어지지 않는다면,

점수 판별에 의해서

1P : Win & Success
2P : Lose & Success

이런 결과를 낼 수 있게 될 듯

2번째 방안.

1P의 승리가 확정 되면 게임 종료 후 결과 보여주기

**Comment by flashscope** [comment]
채택하였습니다.
