### ISSUE TITLE
노래 선택에서 대기열쪽 리스트의 순서 섞임

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#124]
지금 인덱스 번호 % 총 곡수로 표시를 하는데
배열을 잘 나누면 순서대로 잘 표시가 되어줄지
아니면 아예 다른 방법을 써야할지 지금 생각이 잘 안떠오르네요

**Comment by flashscope** [comment]
아 노래가 여러개일때 노래 폴더를 한 6개 만들고 테스트해봐주세요

**Comment by zrma** [comment]
e88673e171be855dbdb81d8d73f41c0f2b901465
곡 선택 문제 해결

6229abd0d37bb3c236321f04f211aaf469b0ef71
테스트용 곡 추가

확인 ㄱㄱ

**Comment by flashscope** [comment]
감사합니다.
