### ISSUE TITLE
Result 버그

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#126]
결과 출력이 정상적으로 이루어지지 않음

2P의 수치 값 위치 문제.

**Comment by flashscope** [comment]
레이블 위치보면 이상이 없는데
2p를 플레이 안하고 000나오면 위치가 이상해지는듯...(초기화 문제_?)
2p에도 스코어 달성하면 정상으로 출력
데이터 초기화 작성후 다시 테스트 해봐야할듯

**Comment by zrma** [comment]
우선 1차적으로 수정하였음.

**Comment by flashscope** [comment]
확인하였습니다.
