### ISSUE TITLE
라벨 관련 버그

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#127]
9143ceb9cace245896d6f9cf6d6dd8fa4de4afa7

우세한 쪽이 커 보이는 코드에서

처음 한 노트가 동시에 내려오고
같이 눌러서 같은 판정에 의해서 동일 점수일 때 한 쪽만 커보이는 문제 발생

**Comment by flashscope** [comment]
고치려면 점수 비교하는데에서 p1->score > p2->score을 p1->score >= p2->score로 바꾸면
동점시에 확인이 가능 하지만 늦게 입력을 한 사람의 기준을 잡아서 둘다 커지는 경우가 발생

즉 해결하려면 printScore안에서 레이블 두개를 동시에 제어해줘야함
그런데 지금 구조상 judge도 다 같은 레이블에서 제어하기 때문에 단순히 레이블 두개 생성한다고 될게 아니라
상대방의 judge도 어딘가에 가지고 있어야함 아니면 printScore를 호출한 주체에 의해 제어되는 구조가 아니라
누가 호출하던 상관없는 구조로 바꿔야함

즉....
그냥 dontfix로 종결하는거 어때요 크게 게임에 영향을 주는 문제도 아니고...

**Comment by zrma** [comment]
확인~

동찬 확인 후 wontfix로 종결

**Comment by trizdreaming** [comment]
확인했습니다.
