### ISSUE TITLE
wstring -> string 문제에 관하여...

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#128]
std::wstring을 std::string으로 변경 시도 하였으나
몇몇 메소드들은 w_char*에 대해 의존적이라 일괄적으로 변경 불가

TinyXML 메소드들이 아스키 코드 의존적이듯
D2D 몇몇 메소드들은 인자를 w_char*로 받는 것들이 많아서
결국 또 변환을 해야 하는 문제가 있어서... 
std::wstring으로 사용하는 것이 더 효율적으로 보임 

리팩토링하면서 조금씩 정리를 해야 하긴 하겠지만
지금처럼 두 가지 형태가 혼재 될 수 밖에 없을 것 같음

**Comment by flashscope** [comment]
확인

**Comment by agebreak** [comment]
근데.. 그 이전에 왜? string으로 바꿀려고 하지? 
요즘 게임의 기본은 유니코드이기 때문에, wstring을 주 문자열로 설정하고 개발하는게 맞음. 
일반 char\* 쓰는곳에서만 변환해주면 됨.
