### ISSUE TITLE
RMObjectManager.cpp

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#131]
CRMobject\* CRMobjectManager::GetObjectFront( LayerType layer ) const
{
        switch ( layer )
        {
        case LAYER_NOTE1:
                if ( m_ObjectListLayerNotePlayer1.size() == 0 )
                {
                        return nullptr; //SM9: 이런거 리턴할때는 밖에서 예외처리 확실하게하도록..
                }

**Comment by zrma** [comment]
예외처리는 되어 있으므로 함수에 주석으로 예외처리를 확실히 하도록 명시
