### ISSUE TITLE
New5 - 1. Danger Zone(line) 적용 및 기능 설정

### ISSUE THREAD

**Issue by trizdreaming** [trizdreaming/oldboy#132]
셔터가 Danger Zone에 닿으면 그 이하는 셔터가 자동으로 내려오며 게임이 종료되도록 함

**Comment by zrma** [comment]
Danger Line에 따른 셔터, 게이지, 아이콘 위치 보정 처리 필요

**Comment by zrma** [comment]
셔터 데드라인 적용
5d4c7efb4c288e9e80962f57178e5accfff72c1e

아이템 데드라인 적용
e40d1fbca43aaac74e99e93bb0204403c9264ada

데드라인 리소스 하나 추가해서 띄워줘야 됨 - Gauge Layer 등의 위치에 대충 넣어도 될 듯

**Comment by zrma** [comment]
전체적으로 설계 사항을 모두 만족하므로 클로즈
