### ISSUE TITLE
RMlabelManager.cpp

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#139]
void CRMlabelManager::AddLabel( std::wstring key , CRMlabel\* label )
{
        SafeDelete( m_LabelMap[key] ); //SM9: 위험하다 만일 key에 해당하는 포인터가 없으면 end() 이터레이터가 반환 될텐데? 그걸 지우면?
        m_LabelMap[key] = label;
}

Map을 배열로 변경하면 같이 해결

**Comment by zrma** [comment]
배열로 변경하였으므로 클로즈
