### ISSUE TITLE
키처리에 관한 리팩토링 필요

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#147]
더이상 지저분해지면...

**Comment by trizdreaming** [comment]
window active api (return true /false ) 를 확인해서 게임이 inactive  상황일때 키를 안 받도록 할 수 있음

**Comment by flashscope** [comment]
활성창에 관한 키처리는 완료
메인루프의 키처리 리펙토링은 다음 마일스톤으로 이동
