### ISSUE TITLE
게이지가 초기화 되지 않는 문제

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#148]
퍼펙트를 하면?

다음 판을 할때 게이지가 꽉차있는 채로 시작합니다.
(Release에서 확인함)

**Comment by trizdreaming** [comment]
확인 했습니다.
초기화 코드 넣을께요~!

**Comment by zrma** [comment]
e3b7cb9c5cb11e0f7c2d6ee5deb5c9681a0e65dd

확인

**Comment by flashscope** [comment]
e3b7cb9
이문제는 아님...

**Comment by trizdreaming** [comment]
완료~!
