### ISSUE TITLE
 라벨 매니저와 라벨 레이어 리팩토링

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#149]
https://github.com/trizdreaming/oldboy/issues/112

https://github.com/trizdreaming/oldboy/issues/105

https://github.com/trizdreaming/oldboy/issues/86

세 이슈 묶어서 함께 처리

**Comment by flashscope** [comment]
#139 
추가

**Comment by trizdreaming** [comment]
이건 다 바뀌었네요;; 스펙 제거 되었습니다.
