### ISSUE TITLE
[week5 feedback] switch-case문 if 문으로 최적화

### ISSUE THREAD

**Issue by trizdreaming** [trizdreaming/oldboy#151]
//SM9: 사실 아래의 PLAYER_ONE과 PLAYER_TWO가 하는 일이 거의 같지? 거의 같은 부분이 있으면 모듈화 하고 재사용하는 것이 좋다
    switch ( player )
    {
    case PLAYER_ONE:
-    // HP üũ�� �̰��
-    // HP 체크는 이곳에서
    if ( CRMplayer1P::GetInstance()->IsDead() )
    {
      break;
    }

**Comment by flashscope** [comment]
https://github.com/trizdreaming/oldboy/commit/fda6509c50e1cca7986cd92dc0a9323974ac79ca

일단 if로 변경을 하였는데 더 최적화를 할지 의견주세요

void CRMjudgeManager::StartNote( PlayerNumber player , ObjectType objectType ) const
{
    CRMobject\* thisNote = CRMobjectManager::GetInstance()->GetObjectFront( LAYER_MEMORY_POOL );
    if ( thisNote == nullptr )
    {
        return; 
    }

```
if ( player == PLAYER_ONE && !CRMplayer1P::GetInstance()->IsDead())
{
    // 만약 이곳에서 HP 체크를 하지 않으면?
    // Judge 메소드 주석 참조
    thisNote->SetObjectType( objectType );
    thisNote->SetPosition( NOTE_ONE_START_POSITION_X, NOTE_START_POSITION_Y );
    thisNote->SetVisible(true);
    thisNote->SetSceneType( SCENE_PLAY );
    CRMobjectManager::GetInstance()->AddObject( thisNote , LAYER_NOTE1 );
    CRMobjectManager::GetInstance()->DeleteNoteListFront( LAYER_MEMORY_POOL );
}
else if ( player == PLAYER_TWO && !CRMplayer2P::GetInstance()->IsDead() )
{
    thisNote->SetObjectType( objectType );
    thisNote->SetPosition( NOTE_TWO_START_POSITION_X, NOTE_START_POSITION_Y );
    thisNote->SetVisible(true);
    thisNote->SetSceneType( SCENE_PLAY );
    CRMobjectManager::GetInstance()->AddObject( thisNote , LAYER_NOTE2 );
    CRMobjectManager::GetInstance()->DeleteNoteListFront( LAYER_MEMORY_POOL );
}
```

}

**Comment by zrma** [comment]
일단 이 메소드는 따로 뽑아서 모듈화 하기가 약간 애매한 것 같음.

**Comment by flashscope** [comment]
확인
