### ISSUE TITLE
MP 올라가는 수치를 유저가 직접?

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#161]
노트가 적은 쉬운 노트에서는 별로 게이지가 안 차는듯
고정된 값이 아닌
유저가 직접 정하거나
노트 수를 보고 계산을 해서 정하던지 해야 할듯...

의견 주세요

**Comment by zrma** [comment]
노트 수를 보고 계산 하는 거 괜찮은 거 같음
