### ISSUE TITLE
아이템 발동! 카드 구현 및 파티클 적용

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#162]
카드 발동 시 파티클 적용 처리 및 아이콘 리소스 변경

**Comment by zrma** [comment]
https://github.com/trizdreaming/oldboy/commit/b96a37eae35f50a33aa97a9abf473d6816d4bd02

파티클 적용 완료

**Comment by zrma** [comment]
확인 후 실제 아이템 별 카드 이미지 적용 부분 구현하셈 :)

**Comment by trizdreaming** [comment]
넹~! 해야죠
