### ISSUE TITLE
[1-D-1] 화면 사운드

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#21]
1-D-1 화면 사운드

**Comment by zrma** [comment]
타이틀 화면 사운드 변경 처리 완료 :)

이 항목은 동찬 확인 후 클로즈 부탁

**Comment by trizdreaming** [comment]
화면 사운드 관련해서 이슈사항이 있습니다.
현재 키 입력 받고난 이후 재생에 문제가 있습니다.

플레이의 지속성 / 멀티쓰레드 문제가 아닌가 싶은데...

테스트 단계에서만 발생하는 문제지만, 원인을 찾고 넘어가는 것이 좋겠습니다.

**Comment by zrma** [comment]
문제 해결 및 클로즈
