### ISSUE TITLE
[1-D-2] 음악 재생 단순 플레이

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#24]
1-D-2 음악 재생 단순 플레이

**Comment by flashscope** [comment]
동작 체크후 클로즈 부탁드립니다.
루프쪽에 임시로 테스트 코드 작성되었습니다.

**Comment by zrma** [comment]
싱글바이트 -> 멀티바이트로 수정하였음. 해당 코드 확인 요망
char -> TCHAR (현재 상황에서는 WCHAR로 써도 됨)
MessageBoxA -> MessageBox(MessageBoxW로 define 되어 있음)
"문자열" -> L"문자열"

MainLoop 생성자에서 생성한 리소스인 Sound를 소멸자에서 해제하도록 해 두었음.
Sound 소멸자에서 Destroy를 호출해서 Fmod의 자원들을 해제하도록 호출

NULL로 초기화 된 포인터들을 nullptr로 초기화 하도록 하였음

해당 리플 확인 후 이슈 클로즈

**Comment by flashscope** [comment]
확인
