### ISSUE TITLE
[1-A-4] 셔터 이동

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#26]
1-A-4 셔터 이동

**Comment by zrma** [comment]
셔터 이동 구현 완료 :)

**Comment by trizdreaming** [comment]
현재 m_Tick 만들어서 시간에 따라 움직이게 하는데요,
이부분 키보드 받는 걸로 바꾸면 수정 가능합니다.(테스트 용으로 시연할거면)

**Comment by zrma** [comment]
1차 릴리즈 완료 하였으므로 해당 이슈는 클로즈 :)
