### ISSUE TITLE
[2-E-1] 판정매니저

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#38]
2-E-1 판정매니저

**Comment by zrma** [comment]
플레이어 노트 리스트의 첫 번째에만 판별을 적용하면

판정 결과가 첫 녀석이 사라지기 전까진 두 번째 세 번째 등에 적용이 안 되므로
아예 전부 미스로 판별 되는 버그가 있음 - 해결 시도 중

**Comment by zrma** [comment]
버그 수정 완료 및 기능 구현 완료 확인

리팩토링 추후
