### ISSUE TITLE
[2-F-1] 배경 생성

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#43]
2-F-1 배경 생성

**Comment by trizdreaming** [comment]
확인하고 닫아주세요~!

**Comment by zrma** [comment]
Result 처리를 하지 않았으므로 3주차로 이전 처리.

**Comment by trizdreaming** [comment]
외부에 맡겼습니다~~

**Comment by zrma** [comment]
https://github.com/trizdreaming/oldboy/issues/68

해당 이슈와 묶어서 함께 처리

**Comment by zrma** [comment]
Result 씬 자체는 생성 하였으므로 클로즈 처리
