### ISSUE TITLE
커밋 할 때 메세지 꼭 남기삼..

### ISSUE THREAD

**Issue by zeliard** [trizdreaming/oldboy#7]
c2d59ba6d80c753fd3defcb8501ec89d1a089f3d
이거 보면... 커밋 할 때 메세지 안남겨 놓은 경우가 있는데..
앞으로 그러면 안된데이..
알긋쟈?

**Comment by zrma** [comment]
알겟심더~

**Comment by trizdreaming** [comment]
옙

**Comment by flashscope** [comment]
네 다 확인했으므로 닫습니다.
