### ISSUE TITLE
헤더 파일 순환 포함 문제

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#77]
oldboy/oldboy/RMinclude.h

요청사항은 주석으로 달아 놓았으니 확인 바람

**Comment by trizdreaming** [comment]
안그래도 작성때 이래도 되나? 했던 부분인데...
그러면 class의 include에 포함 시키는 게 맞는 건가요??

**Comment by zrma** [comment]
확인 후 클로즈 바람

**Comment by trizdreaming** [comment]
확인 완료 되었습니다~!
