### ISSUE TITLE
오브젝트 매니저 추가

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#78]
오브젝트 매니저가 할 일
1. 리스트의 형태로 오브젝트들을 들고 있음
2. CRMmainLoop의 RunMessageLoop 메소드 안에서 타이밍에 맞춰서 오브젝트 매니저의 함수를 호출하면(일정 시간 간격으로 틱을 발생시키면) 자신이 들고 있던 오브젝트들에 Update와 Render를 수행하도록 함

**Comment by zrma** [comment]
일단 간단하게 STL 리스트 추가하여 구현하였음.

각자 확인 바람

**Comment by flashscope** [comment]
확인
남은사항 있나요?

**Comment by zrma** [comment]
일단 이쪽에는 더 이상 없는 듯.
어제 밴드에서 대화 나누었던 것 처럼...

리소스 매니저는 불러올 리소스(현재로는 이미지 파일들)를 한 번에 쫙 다 읽어와서 각 키에 맞게끔 저장해두고, 

오브젝트 매니저는 게임 시작 전에 필요한 오브젝트들을 한 번에 다 미리 만들어두고 저장해 두는 형태로 가면 될 듯.

그리고 오브젝트들이 어디에 저장 되어 있는지를 가리키는 오프셋을 만들거나 해서

대략 ... 배경화면 -> 노트 -> 셔터 -> 레이블

각 요소들 시작점만 구분 지을 수 있거나,
아니면 각 요소들이 필요한 부분(예를 들면 노트의 경우는 노트 관리용 큐라던가)...
즉 각 요소들을 관리할 놈들을, 오브젝트 매니저에서 오브젝트들 만들어둘때 같이 저장하는 방식도 나쁘지 않은 듯
(마치 처음에 노트 생성 할 때 오브젝트 매니저에 저장 되고, 노트 대기 큐에도 저장 되고...
 어차피 이 큐라는 녀석은 동적 메모리 영역에 할당 될 것이고,
 오브젝트 매니저가 들고 있는 리스트든, 아니면 대기 노트들을 관리할 큐든 다 포인터 형태로 저장 될 테니까...)

동찬 확인 후에 클로즈 바람 :)

**Comment by trizdreaming** [comment]
현재 구조 멋집니다^^ 클로즈 합니다.
