### ISSUE TITLE
이펙트 구현 - by 동찬

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#81]
이펙트 구현 (char - 8비트 비트연산 플래그 응용)

**Comment by trizdreaming** [comment]
ㄷㄷㄷ 옵션인거져??=ㅁ=

**Comment by trizdreaming** [comment]
8비트 연산 플래그 응용 부분 완료
움직임은 좌표 받는 부분 확인 후 적용만 하면됩니다.
