### ISSUE TITLE
CRMobject 리팩토링

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#83]
RMJudgeManager.cpp 파일 내용

std::list<CRMobject*>\* notePoolList = CRMobjectManager::GetInstance()->GetObjectList( LAYER_MEMORY_POOL );

```
    //SM9: 풀을 통째로 가져오지 말고 그냥 노트를 하나씩 가져올 수 있도록 CRMobjectManager를 리팩토링 하는게 깔끔.
```

**Comment by flashscope** [comment]
다른 이슈와 묶여서 해결
