### ISSUE TITLE
하드코딩 되어 있는 노트 판정식 define으로 뺴기

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#84]
else if ( (_thisNoteP1)->GetPositionY() > 534 && (_thisNoteP1)->GetPositionY() < 556 ) //SM9: 534, 556같은 상수는 다른곳에 define이나 const int로 빼는게 좋겠지?

**Comment by zrma** [comment]
1. define으로 뽑아낼 것

판정식의 상수 뿐만 아니라
STL 맵에 넣었던 키 값 중

점수 출력 라벨 명(라벨 명이 점수, 콤보 이런 것들임)도 상수 데이터이므로 따로 뽑아내야 할 듯

**Comment by flashscope** [comment]
처리 완료 확인후 클로즈 부탁드립니다.

**Comment by zrma** [comment]
에러 문자열 등등도 처리 완료 하였음.
클로즈!
