### ISSUE TITLE
판정 로직 리팩토링

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#85]
//SM9: 아래를 보면 비슷한 코드의 패턴이 나오고 있네.. 판정 로직을 함수 하나로 일반화 할 수 있을것 같은데? perfect/good/miss 때마다 다른것만 변수로 빼면 될 듯.
                // Player1 Perfect 
                else if ( (_thisNoteP1)->GetPositionY() > 534 && (_thisNoteP1)->GetPositionY() < 556 ) //SM9: 534, 556같은 상수는 다른곳에 define이나 const int로 빼는게 좋겠지?
                { 중략...

**Comment by flashscope** [comment]
이펙트 부분의 버그만 수정이 되면 1단계 완성됨

**Comment by zrma** [comment]
이펙트 부분 리팩토링 완료 및 무한루프 관련 버그 제거함.
코드 리뷰 후 클로즈 확인~

**Comment by flashscope** [comment]
확인
클로즈합니다.
