### ISSUE TITLE
맵이나 리스트 자료구조 쓰는 부분 리팩토링

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#86]
(*labelMap)[key] = this; //SM9: 이건 뭔가 좋은 방법이 아니다. labelMap.Register(key, this) 처럼 등록하게끔 맡기는게 바람직
        //SM9: 그리고 CRMlabelManager에서 CRMlabel의 멤버에 바로 접근할 수 있도록 friend class CRMlabelManager를 선언해주는게 일반적.

friend class CRMlabelManager ;  //SM9: 보통 이런식으로 레이블을 관리하는 메니저가 있다면, 매니저에서는 레이블 안에 그냥 접근가능하게 이런 방식을 많이 쓴다.

std::list<CRMobject*>\*                GetObjectList(LayerType layer);

//SM9: 사실 이렇게 내부 자료구조를 통째로 외부에서 iterate 도는 것도 좋은 구조는 아니다.
// 정 안되면, 오브젝트 하나씩 꺼내서 처리할 수 있도록 GetObjectFirst(), GetObjectNext()식으로 쓰는게 좋다

//SM9: 레이블 매니저가 자신의 데이터를 통째로 리턴하는것은 뭔가 잘못된 구조다.
        //보통은 key를 받아서 내용물을 리턴한다던가 하는 멤버함수를 만들어주는 식으로 되어야 한다.
        // 즉, 레이블 매니저 안에서 뭔가 일을 하도록 해야 함.
        std::map<std::wstring, CRMlabel*>\*        GetLabelMap() { return &m_LabelMap; }

**Comment by zrma** [comment]
STL 라이브러리의 포인터 자체를 리턴하는 형태는 변경 완료 하였음

프렌드 클래스 관련은 추가 처리해야 됨

**Comment by zrma** [comment]
맵은 배열로!

**Comment by flashscope** [comment]
가능한 부분은 다 한것으로 알고 있음

**Comment by flashscope** [comment]
아 확인 필요 헷갈림...
