### ISSUE TITLE
stdafx.h에 라이브러리 pragma 빼기

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#89]
# pragma comment(lib, "dsound.lib") //SM9: 이런 애들은 stdafx.h에 넣지 말기..

**Comment by zrma** [comment]
oldboy.cpp 파일의 main 함수 위 상단에 올려 둠

프로젝트 속성으로 집어넣으면 좋지만, 프로젝트 공동 작업을 할 때 마우스 우클릭을 통해서 일일히 확인하는 번거로움 때문에 실제 한 눈에 파악이 안 되는데 소스 코드 안으로 들어오면 파악하기 용이하므로 해당 위치에 배치.
