### ISSUE TITLE
Win32 console Application to Win32 project

### ISSUE THREAD

**Issue by trizdreaming** [trizdreaming/oldboy#9]
과제 spec과 현재 코드 상태가 다릅니다.

과제에서 제시한 것은 Console이 아니네요.

늦게나마 확인한 것을 다행으로 생각해야 될까요ㅠ

일단 업로드한 코드를 어떻게 삭제하고 새로운 코드들로 바꿀수 있을지 해볼께요.

**Comment by trizdreaming** [comment]
해결 완료 되었습니다.
윈도우는 conflict 해결도 예술이네요;;

조 모임에서 공유하도록 하겠습니다 :)

모두 업데이트 하시기 바랍니다.

**Comment by zrma** [comment]
확인~!

**Comment by flashscope** [comment]
확인. 이슈를 닫습니다.
