### ISSUE TITLE
플레이어 클래스 정리

### ISSUE THREAD

**Issue by zrma** [trizdreaming/oldboy#93]
case PERFECT_COUNT:
                m_PerfectCount = count; //SM9: m_PerfectCount m_GoodCount m_MissCount 이런것들 그냥 m_Count[MAX_COUNT] 처럼 배열 만들어 놓고 쓰는게 깔끔하다.
                break;

**Comment by zrma** [comment]
통합 및 정리 완료

확인 후 클로즈

**Comment by flashscope** [comment]
확인
하지만 어차피 저 값을 판별하거나 다른 데에 쓸것이 아니면 enum보다 define이 좋치않을까요?

일단 클로즈
