### ISSUE TITLE
printf 없애는 방법에 대해...

### ISSUE THREAD

**Issue by flashscope** [trizdreaming/oldboy#98]
d7e395709c0d5bffca71ee6080e8f7b659ccd183

헤더 파일 인크루드 여부를 debug시로 했어도

release시에도 남아있는 printf가 콘솔창이 없어져서 출력할 곳을 못찾을뿐
정상적으로 동작해서 낭비가 이루어 지지 않을까요?

**Comment by zrma** [comment]
RMmacro.h 에서

``` cpp
#ifdef _DEBUG
#define printConsole( c, ... ) printf_s( c, ##__VA_ARGS__ )
#else
#define printConsole( c, ... )
#endif // !_DEBUG
```

이와 같은 형태로 매크로를 이용해 printConsole을 printf_s로 재정의 하였음

디버그 모드가 아닐 경우 printConsole 함수는 정의는 되어 있지만 구현이 되지 않으므로
컴파일러가 소스 상에 아무런 내용도 쓰지 않고 넘어갈 것으로 생각 됨

확인 후 이슈 클로즈 :)

**Comment by flashscope** [comment]
확인하였습니다.
